CREATE TABLE IF NOT EXISTS stats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(255)                            NOT NULL,
    uri        VARCHAR(255)                            NOT NULL,
    ip         VARCHAR(50)                             NOT NULL,
    created_at timestamp                               NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);